#!/usr/bin/env python3
"""Regenerate src/data/registry.ts and refresh question counts in catalog.ts.

catalog.ts is the hand-ordered source of truth for which quizzes exist and in
what order. This script reads it, locates each quiz's data module, and writes a
registry of dynamic imports so a quiz's questions are only downloaded when that
quiz is opened — important because each quiz is iframed into its own lesson.

Run after adding or removing a quiz (import_quiz.py does this automatically).
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "src/data"

ENTRY_RE = re.compile(
    r"\{\s*key:\s*\"(?P<key>[^\"]+)\",.*?course:\s*\"(?P<course>[^\"]+)\",\s*\}",
    re.S,
)


def catalog_entries() -> list[tuple[str, str]]:
    text = (DATA / "catalog.ts").read_text()
    return [(m.group("key"), m.group("course")) for m in ENTRY_RE.finditer(text)]


def find_module(key: str, course: str) -> tuple[str, str, int]:
    """Return (import path, exported symbol, question count)."""
    candidates = (
        [DATA / "intermediate" / f"{key}.ts"]
        if course == "intermediate"
        else sorted(DATA.glob("*.ts"))
    )
    for f in candidates:
        if not f.exists() or f.name in {"types.ts", "catalog.ts", "registry.ts"}:
            continue
        src = f.read_text()
        if not re.search(rf'^\s*key:\s*"{re.escape(key)}",', src, re.M):
            continue
        sym = re.search(r"export const (\w+): Quiz", src)
        if not sym:
            sys.exit(f"{f} has no `export const <name>: Quiz`")
        rel = f.relative_to(DATA).as_posix()[:-3]
        return f"./{rel}", sym.group(1), len(re.findall(r"^\s*correctIndex:", src, re.M))
    sys.exit(f'No data module found for key "{key}" (course {course}).')


def main() -> None:
    entries = catalog_entries()
    if not entries:
        sys.exit("No entries parsed from catalog.ts")

    loaders: dict[str, list[str]] = {"cpa": [], "intermediate": []}
    counts: dict[str, int] = {}
    for key, course in entries:
        path, sym, n = find_module(key, course)
        counts[f"{course}/{key}"] = n
        loaders[course].append(
            f'  "{key}": () =>\n'
            f'    import("{path}").then((m) => m.{sym}),'
        )

    def block(course: str) -> str:
        return "\n".join(loaders[course]) or "  // (none yet)"

    count_lines = "\n".join(
        f'  "{k}": {v},' for k, v in counts.items()
    )

    (DATA / "registry.ts").write_text(f'''// GENERATED by scripts/gen_registry.py — do not edit by hand.
// Run `npm run gen-registry` (or `npm run import-quiz`) to regenerate.
import type {{ Course, Quiz }} from "./types";
import {{ getCatalogForCourse, type QuizCatalogItem }} from "./catalog";

type QuizLoader = () => Promise<Quiz>;

/**
 * Quizzes are loaded on demand. Each one carries a large block of HTML
 * explanations, so bundling them all would make every embedded lesson
 * download every quiz.
 *
 * Keyed per course: a slug may exist in both (e.g. "leases"), and the two
 * are different quizzes.
 */
const loaders: Record<Course, Record<string, QuizLoader>> = {{
  cpa: {{
{block("cpa")}
  }},
  intermediate: {{
{block("intermediate")}
  }},
}};

/** Question counts, generated from the data modules so the index pages can
 *  show them without downloading every quiz. */
const questionCounts: Record<string, number> = {{
{count_lines}
}};

export interface HomeQuizLink extends QuizCatalogItem {{
  available: boolean;
  questionCount: number | null;
  href: string;
}}

/** URL a quiz is served from. Intermediate quizzes are namespaced. */
export function quizHref(item: Pick<QuizCatalogItem, "key" | "course">): string {{
  return item.course === "intermediate"
    ? `/intermediate/${{item.key}}`
    : `/${{item.key}}`;
}}

/** Quiz links for one course's index page. Courses never cross-link. */
export function getHomeQuizLinks(course: Course = "cpa"): HomeQuizLink[] {{
  return getCatalogForCourse(course).map((item) => {{
    const count = questionCounts[`${{course}}/${{item.key}}`] ?? null;
    return {{
      ...item,
      available: !!loaders[course][item.key],
      questionCount: count,
      href: quizHref(item),
    }};
  }});
}}

/** Loader for one quiz, or null when the slug is not in that course. */
export function getQuizLoader(
  key: string | undefined,
  course: Course = "cpa",
): QuizLoader | null {{
  if (!key) return null;
  return loaders[course][key] ?? null;
}}

/** Course a URL path belongs to. */
export function courseForPath(pathname: string): Course {{
  return pathname.startsWith("/intermediate") ? "intermediate" : "cpa";
}}

export {{
  quizCatalog,
  cpaCatalog,
  intermediateCatalog,
  getCatalogForCourse,
  getCatalogItem,
}} from "./catalog";
''')

    n_cpa, n_int = len(loaders["cpa"]), len(loaders["intermediate"])
    print(f"registry.ts: {n_cpa} CPA + {n_int} intermediate quizzes, "
          f"{sum(counts.values())} questions")


if __name__ == "__main__":
    main()
