/**
 * Simulations, kept deliberately outside catalog.ts and registry.ts.
 *
 * registry.ts is generated by scripts/gen_registry.py, which walks catalog.ts
 * and expects every entry to resolve to an `export const <name>: Quiz`. A sim
 * listed there would fail that lookup and be wiped on the next
 * `npm run import-quiz`. This file is small, hand-maintained, and safe.
 */
import type { Sim } from "../types";

export interface SimCatalogItem {
  key: string;
  title: string;
  subtitle: string;
  discipline: Sim["discipline"];
}

/** Listed on the home page under the official AICPA items. */
export const simCatalog: SimCatalogItem[] = [
  {
    key: "aicpa-far-tbs-110110",
    title: "Official AICPA FAR Simulation: Blear Co.",
    subtitle: "Adjust a consolidated balance sheet from seven exhibits",
    discipline: "far",
  },
];

/** Loaded on demand: the exhibits are a large block of HTML. */
const loaders: Record<string, () => Promise<Sim>> = {
  "aicpa-far-tbs-110110": () =>
    import("./aicpa-far-tbs-110110").then((m) => m.aicpaFarTbs110110),
};

export function getSimLoader(key: string | undefined): (() => Promise<Sim>) | null {
  if (!key) return null;
  return loaders[key] ?? null;
}

export function getSimCatalogItem(key: string | undefined): SimCatalogItem | null {
  return simCatalog.find((s) => s.key === key) ?? null;
}

export function simHref(key: string): string {
  return `/${key}`;
}

export function isSimKey(key: string | undefined): boolean {
  return !!key && key in loaders;
}

/**
 * The sim key for a URL path.
 *
 * Netlify serves the pre-rendered `dist/<key>/index.html` and redirects the
 * bare path to one with a trailing slash, so the browser's pathname is
 * "/aicpa-far-tbs-110110/" in production and "/aicpa-far-tbs-110110" in dev.
 * Both have to resolve, which is why this trims rather than slicing one
 * leading character.
 */
export function simKeyFromPath(pathname: string): string {
  return pathname.replace(/^\/+|\/+$/g, "");
}
