// GENERATED by scripts/gen_registry.py — do not edit by hand.
// Run `npm run gen-registry` (or `npm run import-quiz`) to regenerate.
import type { Course, Quiz } from "./types";
import { getCatalogForCourse, type QuizCatalogItem } from "./catalog";

type QuizLoader = () => Promise<Quiz>;

/**
 * Quizzes are loaded on demand. Each one carries a large block of HTML
 * explanations, so bundling them all would make every embedded lesson
 * download every quiz.
 *
 * Keyed per course: a slug may exist in both (e.g. "leases"), and the two
 * are different quizzes.
 */
const loaders: Record<Course, Record<string, QuizLoader>> = {
  cpa: {
  "aicpa-far-2026": () =>
    import("./aicpa-far-2026").then((m) => m.aicpaFar2026Quiz),
  "aicpa-aud-2026": () =>
    import("./aicpa-aud-2026").then((m) => m.aicpaAud2026Quiz),
  "aicpa-reg-2026": () =>
    import("./aicpa-reg-2026").then((m) => m.aicpaReg2026Quiz),
  "most-common-far": () =>
    import("./most-common-far").then((m) => m.mostCommonFarQuiz),
  "most-common-aud": () =>
    import("./most-common-aud").then((m) => m.mostCommonAudQuiz),
  "most-common-reg": () =>
    import("./most-common-reg").then((m) => m.mostCommonRegQuiz),
  "cashtoaccrual": () =>
    import("./cash-to-accrual").then((m) => m.cashToAccrualQuiz),
  "ratios": () =>
    import("./ratios").then((m) => m.ratiosQuiz),
  "leases": () =>
    import("./leases").then((m) => m.leasesQuiz),
  },
  intermediate: {
  "conceptual-framework": () =>
    import("./intermediate/conceptual-framework").then((m) => m.conceptualFrameworkQuiz),
  "adjusting-entries": () =>
    import("./intermediate/adjusting-entries").then((m) => m.adjustingEntriesQuiz),
  "financial-statements": () =>
    import("./intermediate/financial-statements").then((m) => m.financialStatementsQuiz),
  "time-value-of-money": () =>
    import("./intermediate/time-value-of-money").then((m) => m.timeValueOfMoneyQuiz),
  "revenue-recognition": () =>
    import("./intermediate/revenue-recognition").then((m) => m.revenueRecognitionQuiz),
  "cash": () =>
    import("./intermediate/cash").then((m) => m.cashQuiz),
  "accounts-receivable": () =>
    import("./intermediate/accounts-receivable").then((m) => m.accountsReceivableQuiz),
  "inventory": () =>
    import("./intermediate/inventory").then((m) => m.inventoryQuiz),
  "ppe": () =>
    import("./intermediate/ppe").then((m) => m.ppeQuiz),
  "intangibles": () =>
    import("./intermediate/intangibles").then((m) => m.intangiblesQuiz),
  "payables": () =>
    import("./intermediate/payables").then((m) => m.payablesQuiz),
  "contingencies": () =>
    import("./intermediate/contingencies").then((m) => m.contingenciesQuiz),
  "bonds": () =>
    import("./intermediate/bonds").then((m) => m.bondsQuiz),
  "investments": () =>
    import("./intermediate/investments").then((m) => m.investmentsQuiz),
  "stockholders-equity": () =>
    import("./intermediate/stockholders-equity").then((m) => m.stockholdersEquityQuiz),
  "earnings-per-share": () =>
    import("./intermediate/earnings-per-share").then((m) => m.earningsPerShareQuiz),
  "leases": () =>
    import("./intermediate/leases").then((m) => m.leasesQuiz),
  "income-taxes": () =>
    import("./intermediate/income-taxes").then((m) => m.incomeTaxesQuiz),
  "accounting-changes": () =>
    import("./intermediate/accounting-changes").then((m) => m.accountingChangesQuiz),
  "statement-of-cash-flows": () =>
    import("./intermediate/statement-of-cash-flows").then((m) => m.statementOfCashFlowsQuiz),
  },
};

/** Question counts, generated from the data modules so the index pages can
 *  show them without downloading every quiz. */
const questionCounts: Record<string, number> = {
  "cpa/aicpa-far-2026": 25,
  "cpa/aicpa-aud-2026": 39,
  "cpa/aicpa-reg-2026": 36,
  "cpa/most-common-far": 10,
  "cpa/most-common-aud": 10,
  "cpa/most-common-reg": 10,
  "cpa/cashtoaccrual": 10,
  "cpa/ratios": 10,
  "cpa/leases": 10,
  "intermediate/conceptual-framework": 10,
  "intermediate/adjusting-entries": 10,
  "intermediate/financial-statements": 10,
  "intermediate/time-value-of-money": 10,
  "intermediate/revenue-recognition": 10,
  "intermediate/cash": 10,
  "intermediate/accounts-receivable": 10,
  "intermediate/inventory": 10,
  "intermediate/ppe": 10,
  "intermediate/intangibles": 10,
  "intermediate/payables": 10,
  "intermediate/contingencies": 10,
  "intermediate/bonds": 10,
  "intermediate/investments": 10,
  "intermediate/stockholders-equity": 10,
  "intermediate/earnings-per-share": 10,
  "intermediate/leases": 10,
  "intermediate/income-taxes": 10,
  "intermediate/accounting-changes": 10,
  "intermediate/statement-of-cash-flows": 10,
};

export interface HomeQuizLink extends QuizCatalogItem {
  available: boolean;
  questionCount: number | null;
  href: string;
}

/** URL a quiz is served from. Intermediate quizzes are namespaced. */
export function quizHref(item: Pick<QuizCatalogItem, "key" | "course">): string {
  return item.course === "intermediate"
    ? `/intermediate/${item.key}`
    : `/${item.key}`;
}

/** Quiz links for one course's index page. Courses never cross-link. */
export function getHomeQuizLinks(course: Course = "cpa"): HomeQuizLink[] {
  return getCatalogForCourse(course).map((item) => {
    const count = questionCounts[`${course}/${item.key}`] ?? null;
    return {
      ...item,
      available: !!loaders[course][item.key],
      questionCount: count,
      href: quizHref(item),
    };
  });
}

/** Loader for one quiz, or null when the slug is not in that course. */
export function getQuizLoader(
  key: string | undefined,
  course: Course = "cpa",
): QuizLoader | null {
  if (!key) return null;
  return loaders[course][key] ?? null;
}

/** Course a URL path belongs to. */
export function courseForPath(pathname: string): Course {
  return pathname.startsWith("/intermediate") ? "intermediate" : "cpa";
}

export {
  quizCatalog,
  cpaCatalog,
  intermediateCatalog,
  getCatalogForCourse,
  getCatalogItem,
} from "./catalog";
